implement

diff --git a/bin/skipjack b/bin/skipjack
--- a/bin/skipjack
+++ b/bin/skipjack
@@ -6,7 +6,7 @@ MC_BIN_URL="https://dl.min.io/client/mc/release/linux-amd64/mc"
 MC_BIN_PATH="$(which mc 2>/dev/null ||:)"
 MC_DIR="${HOME}/.mc"
 MC_BIN_DIR="${MC_DIR}/bin"
-ENVFILE="${MC_DIR}/.env"
+CONFIG_FILE="${MC_DIR}/config"
 
 WORKDIR="$( cd "$( dirname "$0" )" && pwd -P)"
 
@@ -14,43 +14,80 @@ WORKDIR="$( cd "$( dirname "$0" )" && pwd -P)"
 check_and_install_mc() {
   if [[ -z ${MC_BIN_PATH} ]]; then
     MC_BIN_PATH="${MC_BIN_DIR}/mc"
-    if [[ ! -e ${MC_BIN_DIR}/mc ]]; then
-      echo "mc command not found: installing at ${MC_BIN_DIR} .."
+    if [[ ! -e ${MC_BIN_PATH} ]]; then
+      echo "mc command not found: installing at ${MC_BIN_DIR} .." 1>&2
       mkdir -p ${MC_BIN_DIR}
       cd ${MC_BIN_DIR}
       curl -s ${MC_BIN_URL} > ${MC_BIN_PATH}
       chmod +x ${MC_BIN_PATH}
+
+      create_config_file_template
+      echo "Edit ${CONFIG_FILE} file as follows to start using mc command:"
+      config_file_instruction
+      exit 0
     fi
   fi
-  echo "Using mc command at ${MC_BIN_PATH} .."
+  echo "Using mc command at ${MC_BIN_PATH} .." 1>&2
 }
 
-check_env_and_parse() {
-  if [[ ! -e "${ENVFILE}" ]]; then
-    echo "ERROR: ${ENVFILE} not found. Create and fill connection info as follows:"
-    echo "ALIAS=<minio_server_alias>"
-    echo "URL=<minio_server_url>"
-    echo "ACCESSKEY=<access_key>"
-    echo "SECRETKEY=<secret_key>"
+check_config_file() {
+  if [[ ! -e "${CONFIG_FILE}" ]]; then
+    create_config_file_template
+    echo "ERROR: Configuration unavailable. Edit ${CONFIG_FILE} and fill connection info as follows:" 1>&2
+    config_file_instruction
     exit 1
   fi
-  MINIO_ALIAS="$(grep 'ALIAS' ${ENVFILE} | cut -d '=' -f 2)"
-  MINIO_URL="$(grep 'URL' ${ENVFILE} | cut -d '=' -f 2)"
-  MINIO_ACCESSKEY="$(grep 'ACCESSKEY' ${ENVFILE} | cut -d '=' -f 2)"
-  MINIO_SECRETKEY="$(grep 'SECRETKEY' ${ENVFILE} | cut -d '=' -f 2)"
+}
+
+create_config_file_template() {
+  echo "ALIAS=" >> ${CONFIG_FILE}
+  echo "URL=" >> ${CONFIG_FILE}
+  echo "ACCESSKEY=" >> ${CONFIG_FILE}
+  echo "SECRETKEY=" >> ${CONFIG_FILE}
+}
+
+config_file_instruction() {
+  echo "ALIAS=<minio_server_alias>" 1>&2
+  echo "URL=<minio_server_url>" 1>&2
+  echo "ACCESSKEY=<access_key>" 1>&2
+  echo "SECRETKEY=<secret_key>" 1>&2
+  exit 0
+}
+
+show_config_file() {
+  check_config_file
+  cat "${CONFIG_FILE}"
+}
+
+parse_config_file() {
+  check_config_file
+  MINIO_ALIAS="$(grep 'ALIAS' ${CONFIG_FILE} | cut -d '=' -f 2)"
+  MINIO_URL="$(grep 'URL' ${CONFIG_FILE} | cut -d '=' -f 2)"
+  MINIO_ACCESSKEY="$(grep 'ACCESSKEY' ${CONFIG_FILE} | cut -d '=' -f 2)"
+  MINIO_SECRETKEY="$(grep 'SECRETKEY' ${CONFIG_FILE} | cut -d '=' -f 2)"
 }
 
 set_minio_alias() {
-  check_env_and_parse
-  no_alias=$(${MC_BIN_PATH} alas ls ${MINIO_ALIAS} | grep ERROR ||:)
-  if [[ -z ${no_alias} ]]; then
-    echo "Setting minio alias.."
+  parse_config_file
+  no_alias=$(${MC_BIN_PATH} alias ls ${MINIO_ALIAS} 2>&1 | grep ERROR ||:)
+  if [[ ! -z ${no_alias} ]]; then
+    echo "Setting minio alias.." 1>&2
     ${MC_BIN_PATH} alias set ${MINIO_ALIAS} ${MINIO_URL} ${MINIO_ACCESSKEY} ${MINIO_SECRETKEY}
   fi
 }
 
 copy() {
   echo "copy"
+  echo $@
+}
+
+mirror() {
+  echo "mirror"
+  echo $@
+}
+
+mc_cmd() {
+  ${MC_BIN_PATH} $@
 }
 
 clean_mc_dir() {
@@ -66,7 +103,7 @@ cat <<EOS
 $(version)
 
 Usage:
-  skipjack [subcommand] <file..>
+  skipjack [subcommand] [source<local file>] [target<storage server>]
 
 Subcommand:
   cp                      Copy files to the storage
@@ -80,7 +117,6 @@ EOS
 }
 
 main() {
-  check_and_install_mc
   if [[ $# -eq 0 ]]; then
     help
     exit 0
@@ -95,24 +131,67 @@ main() {
         help
         exit 0
         ;;
-      cp)
-        shift
-        set_minio_alias
-        ;;
-      mc)
-        shift
-        set_minio_alias
-        ${MC_BIN_PATH} $@
-        exit 0
-        ;;
-      mirror)
-        shift
-        set_minio_alias
-        ;;
       clean)
         echo "Deleting ${MC_DIR} .."
         rm -fr ${MC_DIR}
         exit 0
+        ;;
+      env)
+        show_config_file
+        exit 0
+        ;;
+      mc)
+        CMD="mc"
+        ;;
+      cp)
+        CMD="copy"
+        ;;
+      mirror)
+        CMD="mirror"
+        ;;
+      *)
+        help
+        exit 0
+        ;;
+    esac
+    shift
+  fi
+
+  check_and_install_mc
+  set_minio_alias
+
+  if [[ ${CMD} == "mc" ]]; then
+    mc_cmd $@
+  else
+    if [[ $# -lt 2 ]]; then
+      echo "ERROR: invalid number of arguments" 2>&1
+      echo "Usage: skipjack ${CMD} <file>... <bucket>" 2>&1
+      exit 1
+    fi
+
+    FILES=()
+    while [[ $# -gt 1 ]]; do
+      arg=${1}
+      case ${arg} in
+        --bucket|-b)
+          BUCKET=${2}
+          shift
+          ;;
+        *)
+          FILES+=("${1}")
+          ;;
+      esac
+      shift
+    done
+
+    set -- "${FILES[@]}"
+
+    case ${CMD} in
+      cp)
+        copy $@
+        ;;
+      mirror)
+        mirror $@
         ;;
     esac
   fi
